-- views.sql — הגדרות התצוגות של הקטלוג (DuckDB). נוצר אוטומטית על ידי engines/pull_options.py — לא לערוך ידנית.
-- תיעוד: catalog/open_catalog.py מריץ את אותן הגדרות בדיוק, כש-<OPTIONS_DIR> ו-<MARKET_DIR> מוחלפים בנתיבים מוחלטים שנפתרים
-- ברגע הקריאה (<OPTIONS_DIR> — שורש trading-options-data; <MARKET_DIR> — שורש trading-market-data, העותק האח).
-- תצוגה שאין לה קבצים נוצרת ריקה, עם כל העמודות (ההגדרה שבהערה "אין קבצים").
SET TimeZone='America/New_York';

-- options_eod: שרשראות סוף-יום אחרי הסינון — מאגר האופציות, `eod/<סמל>/<שנה-חודש>.parquet`
CREATE OR REPLACE VIEW options_eod AS SELECT underlying AS symbol, * FROM read_parquet('<OPTIONS_DIR>/eod/*/*.parquet', union_by_name=true);
-- אין קבצים: CREATE OR REPLACE VIEW options_eod AS SELECT NULL::VARCHAR AS "symbol", NULL::VARCHAR AS "option_symbol", NULL::VARCHAR AS "underlying", NULL::DATE AS "session", NULL::DATE AS "expiration", NULL::VARCHAR AS "side", NULL::DOUBLE AS "strike", NULL::DOUBLE AS "bid", NULL::DOUBLE AS "ask", NULL::DOUBLE AS "mid", NULL::BIGINT AS "bid_size", NULL::BIGINT AS "ask_size", NULL::DOUBLE AS "open", NULL::DOUBLE AS "high", NULL::DOUBLE AS "low", NULL::DOUBLE AS "close", NULL::BIGINT AS "volume", NULL::BIGINT AS "trades", NULL::DOUBLE AS "open_interest", NULL::BOOLEAN AS "oi_asof_prev_close", NULL::BOOLEAN AS "crossed", NULL::TIMESTAMP WITH TIME ZONE AS "quote_time", NULL::TIMESTAMP WITH TIME ZONE AS "last_trade", NULL::TIMESTAMP WITH TIME ZONE AS "created", NULL::BIGINT AS "dte", NULL::DOUBLE AS "T_years", NULL::DOUBLE AS "risk_free", NULL::DOUBLE AS "iv_calc", NULL::DOUBLE AS "delta_calc", NULL::VARCHAR AS "kept_by", NULL::BIGINT AS "filter_version", NULL::DOUBLE AS "spot_raw", NULL::VARCHAR AS "spot_source", NULL::VARCHAR AS "price_basis", NULL::VARCHAR AS "model_version" WHERE 1=0;

-- options_intraday: תמונות שרשרת בנקודות קבועות ביום, אחרי הסינון — מאגר האופציות, `intraday/<סמל>/<שנה-חודש>.parquet`
CREATE OR REPLACE VIEW options_intraday AS SELECT underlying AS symbol, * FROM read_parquet('<OPTIONS_DIR>/intraday/*/*.parquet', union_by_name=true);
-- אין קבצים: CREATE OR REPLACE VIEW options_intraday AS SELECT NULL::VARCHAR AS "symbol", NULL::VARCHAR AS "option_symbol", NULL::VARCHAR AS "underlying", NULL::DATE AS "session", NULL::DATE AS "expiration", NULL::VARCHAR AS "side", NULL::DOUBLE AS "strike", NULL::DOUBLE AS "bid", NULL::DOUBLE AS "ask", NULL::DOUBLE AS "mid", NULL::BIGINT AS "bid_size", NULL::BIGINT AS "ask_size", NULL::BOOLEAN AS "crossed", NULL::TIMESTAMP WITH TIME ZONE AS "snapshot_time", NULL::TIMESTAMP WITH TIME ZONE AS "quote_time", NULL::DOUBLE AS "lag_sec", NULL::DOUBLE AS "open_interest", NULL::BOOLEAN AS "oi_asof_prev_close", NULL::VARCHAR AS "point", NULL::BIGINT AS "dte", NULL::DOUBLE AS "T_years", NULL::DOUBLE AS "risk_free", NULL::DOUBLE AS "iv_calc", NULL::DOUBLE AS "delta_calc", NULL::VARCHAR AS "kept_by", NULL::BIGINT AS "filter_version", NULL::DOUBLE AS "spot_raw", NULL::VARCHAR AS "spot_source", NULL::VARCHAR AS "price_basis", NULL::VARCHAR AS "model_version" WHERE 1=0;

-- candles_daily: נרות יומיים **מותאמים** לדיבידנד ולפיצול — מאגר נתוני השוק, `daily/<סמל>.csv`
CREATE OR REPLACE VIEW candles_daily AS SELECT regexp_extract(filename, '([A-Za-z0-9._-]+)\.(csv|parquet)$', 1) AS symbol, time_ny::DATE AS session, open, high, low, close, volume FROM read_csv('<MARKET_DIR>/daily/*.csv', header=true, filename=true, types={'time_ny': 'VARCHAR', 'open': 'DOUBLE', 'high': 'DOUBLE', 'low': 'DOUBLE', 'close': 'DOUBLE', 'volume': 'DOUBLE'});
-- אין קבצים: CREATE OR REPLACE VIEW candles_daily AS SELECT NULL::VARCHAR AS "symbol", NULL::DATE AS "session", NULL::DOUBLE AS "open", NULL::DOUBLE AS "high", NULL::DOUBLE AS "low", NULL::DOUBLE AS "close", NULL::DOUBLE AS "volume" WHERE 1=0;

-- candles_daily_raw: נרות יומיים **גולמיים** + גורם התאמה — מאגר נתוני השוק, `daily_raw/<סמל>.csv`
CREATE OR REPLACE VIEW candles_daily_raw AS SELECT regexp_extract(filename, '([A-Za-z0-9._-]+)\.(csv|parquet)$', 1) AS symbol, time_ny::DATE AS session, open, high, low, close, volume, adj_factor FROM read_csv('<MARKET_DIR>/daily_raw/*.csv', header=true, filename=true, types={'time_ny': 'VARCHAR', 'open': 'DOUBLE', 'high': 'DOUBLE', 'low': 'DOUBLE', 'close': 'DOUBLE', 'volume': 'DOUBLE', 'adj_factor': 'DOUBLE'});
-- אין קבצים: CREATE OR REPLACE VIEW candles_daily_raw AS SELECT NULL::VARCHAR AS "symbol", NULL::DATE AS "session", NULL::DOUBLE AS "open", NULL::DOUBLE AS "high", NULL::DOUBLE AS "low", NULL::DOUBLE AS "close", NULL::DOUBLE AS "volume", NULL::DOUBLE AS "adj_factor" WHERE 1=0;

-- candles_30m: נרות 30 דקות (גולמיים לדיבידנד, מותאמים לפיצול) — מאגר נתוני השוק, `intraday30/<סמל>.csv`
CREATE OR REPLACE VIEW candles_30m AS SELECT regexp_extract(filename, '([A-Za-z0-9._-]+)\.(csv|parquet)$', 1) AS symbol, time_ny::TIMESTAMPTZ AS time_ny, open, high, low, close, volume FROM read_csv('<MARKET_DIR>/intraday30/*.csv', header=true, filename=true, types={'time_ny': 'VARCHAR', 'open': 'DOUBLE', 'high': 'DOUBLE', 'low': 'DOUBLE', 'close': 'DOUBLE', 'volume': 'DOUBLE'});
-- אין קבצים: CREATE OR REPLACE VIEW candles_30m AS SELECT NULL::VARCHAR AS "symbol", NULL::TIMESTAMP WITH TIME ZONE AS "time_ny", NULL::DOUBLE AS "open", NULL::DOUBLE AS "high", NULL::DOUBLE AS "low", NULL::DOUBLE AS "close", NULL::DOUBLE AS "volume" WHERE 1=0;

-- vix_family: משפחת ה-VIX (CBOE), יומי — מאגר נתוני השוק, `cboe/<מדד>.csv`
CREATE OR REPLACE VIEW vix_family AS SELECT regexp_extract(filename, '([A-Za-z0-9._-]+)\.(csv|parquet)$', 1) AS symbol, time_ny::DATE AS session, open, high, low, close FROM read_csv('<MARKET_DIR>/cboe/*.csv', header=true, filename=true, types={'time_ny': 'VARCHAR', 'open': 'DOUBLE', 'high': 'DOUBLE', 'low': 'DOUBLE', 'close': 'DOUBLE'});
-- אין קבצים: CREATE OR REPLACE VIEW vix_family AS SELECT NULL::VARCHAR AS "symbol", NULL::DATE AS "session", NULL::DOUBLE AS "open", NULL::DOUBLE AS "high", NULL::DOUBLE AS "low", NULL::DOUBLE AS "close" WHERE 1=0;

-- corporate_actions: פיצולים — מאגר האופציות, `corporate_actions.csv`
CREATE OR REPLACE VIEW corporate_actions AS SELECT * FROM read_csv('<OPTIONS_DIR>/corporate_actions.csv', header=true, types={'symbol': 'VARCHAR', 'date': 'DATE', 'ratio': 'DOUBLE', 'source': 'VARCHAR', 'verified': 'VARCHAR', 'verified_by': 'VARCHAR', 'note': 'VARCHAR'});
-- אין קבצים: CREATE OR REPLACE VIEW corporate_actions AS SELECT NULL::VARCHAR AS "symbol", NULL::DATE AS "date", NULL::DOUBLE AS "ratio", NULL::VARCHAR AS "source", NULL::VARCHAR AS "verified", NULL::VARCHAR AS "verified_by", NULL::VARCHAR AS "note" WHERE 1=0;

-- contracts_watch: חוזים במעקב — נשמרים עד פקיעתם גם מחוץ למסננים; מאגר האופציות, `contracts_watch.csv`
CREATE OR REPLACE VIEW contracts_watch AS SELECT * FROM read_csv('<OPTIONS_DIR>/contracts_watch.csv', header=true, types={'option_symbol': 'VARCHAR', 'underlying': 'VARCHAR', 'expiration': 'DATE', 'side': 'VARCHAR', 'strike': 'DOUBLE', 'added_ny': 'VARCHAR', 'note': 'VARCHAR'});
-- אין קבצים: CREATE OR REPLACE VIEW contracts_watch AS SELECT NULL::VARCHAR AS "option_symbol", NULL::VARCHAR AS "underlying", NULL::DATE AS "expiration", NULL::VARCHAR AS "side", NULL::DOUBLE AS "strike", NULL::VARCHAR AS "added_ny", NULL::VARCHAR AS "note" WHERE 1=0;

-- files: קובצי הנתונים של מאגר האופציות — מהמניפסט (`manifest.json`): הכיסוי והאיכות של כל קובץ, בלי לפתוח אותו
CREATE OR REPLACE VIEW files AS WITH m AS (SELECT content::JSON AS j FROM read_text('<OPTIONS_DIR>/manifest.json')), k AS (SELECT j, unnest(json_keys(j, '$.files')) AS file FROM m), f AS (SELECT file, json_extract(j, '$.files."' || file || '"') AS v FROM k) SELECT CAST(file AS VARCHAR) AS "file", CAST(v->>'symbol' AS VARCHAR) AS "symbol", CAST(v->>'kind' AS VARCHAR) AS "data_kind", CAST(v->>'month' AS VARCHAR) AS "month", CAST(v->>'sessions' AS BIGINT) AS "sessions", CAST(v->>'rows' AS BIGINT) AS "rows", CAST(v->>'first_session' AS DATE) AS "first_session", CAST(v->>'last_session' AS DATE) AS "last_session", CAST(v->>'complete' AS BOOLEAN) AS "complete", CAST(v->>'oi_rows_pct' AS DOUBLE) AS "oi_rows_pct", CAST(v->'spot_sources'->>'stock_eod_raw' AS BIGINT) AS "spot_stock_eod_raw", CAST(v->'spot_sources'->>'candles_30m' AS BIGINT) AS "spot_candles_30m", CAST(v->'spot_sources'->>'parity' AS BIGINT) AS "spot_parity", CAST(v->'spot_sources'->>'none' AS BIGINT) AS "spot_none", CAST(v->>'contracts_per_day_median' AS DOUBLE) AS "contracts_median", CAST(v->>'contracts_per_day_median_total' AS DOUBLE) AS "contracts_median_total", CAST(v->'alarm'->>'count' AS BIGINT) AS "alarm_count", CAST(v->'alarm'->>'max' AS BIGINT) AS "alarm_max", CAST(v->>'filter_version' AS BIGINT) AS "filter_version", CAST(v->>'retention' AS VARCHAR) AS "retention", CAST(v->>'updated_ny' AS VARCHAR) AS "updated_ny" FROM f;
-- אין קבצים: CREATE OR REPLACE VIEW files AS SELECT NULL::VARCHAR AS "file", NULL::VARCHAR AS "symbol", NULL::VARCHAR AS "data_kind", NULL::VARCHAR AS "month", NULL::BIGINT AS "sessions", NULL::BIGINT AS "rows", NULL::DATE AS "first_session", NULL::DATE AS "last_session", NULL::BOOLEAN AS "complete", NULL::DOUBLE AS "oi_rows_pct", NULL::BIGINT AS "spot_stock_eod_raw", NULL::BIGINT AS "spot_candles_30m", NULL::BIGINT AS "spot_parity", NULL::BIGINT AS "spot_none", NULL::DOUBLE AS "contracts_median", NULL::DOUBLE AS "contracts_median_total", NULL::BIGINT AS "alarm_count", NULL::BIGINT AS "alarm_max", NULL::BIGINT AS "filter_version", NULL::VARCHAR AS "retention", NULL::VARCHAR AS "updated_ny" WHERE 1=0;

-- known_gaps: החורים הידועים — מהמניפסט: ימי מסחר (`point` ריק) ונקודות תוך-יומיות שהספק נשאל עליהם ולא החזיר, עם הסיבה
CREATE OR REPLACE VIEW known_gaps AS WITH m AS (SELECT content::JSON AS j FROM read_text('<OPTIONS_DIR>/manifest.json')), s AS (SELECT j, unnest(json_keys(j, '$.symbols')) AS symbol FROM m), k AS (SELECT j, symbol, unnest(['eod', 'intraday']) AS data_kind FROM s), mo AS (SELECT j, symbol, data_kind, unnest(json_keys(j, '$.symbols."' || symbol || '".' || data_kind || '.known_gaps')) AS month FROM k), d AS (SELECT j, symbol, data_kind, month, unnest(json_keys(j, '$.symbols."' || symbol || '".' || data_kind || '.known_gaps' || '."' || month || '"')) AS day FROM mo), pf AS (SELECT j, unnest(json_keys(j, '$.files')) AS file FROM m), pd AS (SELECT j, file, unnest(json_keys(j, '$.files."' || file || '"' || '.point_gaps')) AS day FROM pf), pp AS (SELECT j, file, day, unnest(json_keys(j, '$.files."' || file || '"' || '.point_gaps."' || day || '"')) AS point FROM pd) SELECT symbol::VARCHAR AS symbol, data_kind::VARCHAR AS data_kind, CAST(day AS DATE) AS gap_date, NULL::VARCHAR AS point, json_extract_string(j, '$.symbols."' || symbol || '".' || data_kind || '.known_gaps' || '."' || month || '"."' || day || '"') AS reason FROM d UNION ALL SELECT json_extract_string(j, '$.files."' || file || '"' || '.symbol'), json_extract_string(j, '$.files."' || file || '"' || '.kind'), CAST(day AS DATE), point::VARCHAR, json_extract_string(j, '$.files."' || file || '"' || '.point_gaps."' || day || '"."' || point || '"') FROM pp;
-- אין קבצים: CREATE OR REPLACE VIEW known_gaps AS SELECT NULL::VARCHAR AS "symbol", NULL::VARCHAR AS "data_kind", NULL::DATE AS "gap_date", NULL::VARCHAR AS "point", NULL::VARCHAR AS "reason" WHERE 1=0;

-- catalog_info: גרסת המבנה והשעה
CREATE OR REPLACE VIEW catalog_info AS SELECT 'options-data/1' AS schema, current_timestamp AS built_at;
